### ISSUE TITLE
Who to propagate updates to?

### ISSUE THREAD

**Issue by jamii** [matthias-brun/progress-tracking-formalization#1]
At 432 it says work is only propagated to the immediate successors, but the code for propagate in the paper and also in https://www.isa-afp.org/browser_info/current/AFP/Progress_Tracking/document.pdf seems to propagate to all other nodes.

![image](https://user-images.githubusercontent.com/340884/117526567-ef43c900-af7a-11eb-8436-3819ed0846ff.png)

Am I misreading this?

**Comment by dtraytel** [comment]
Thanks for the question. The formal specification expresses the written statement, albeit in a slightly implicit way. The key is that here `summary` is used (as opposed to `path_summary`). In particular, `summary` is only non-empty for the immediate successors `l'` of a fixed `l`. Thus, the worklists will not change for locations `l'` that are not immediate successors of `l` (because `_ funny_asymmetric_oplus_symbol {}_A = {#}_z`).

**Comment by jamii** [comment]
Ah, that makes sense. Thanks!
